config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :user
  devise_scope :user do
    get 'admin', to: 'devise/sessions#new'
    post 'admin', to: 'devise/sessions#create'
  end
  resources :animals do
    get 'adopt', to: 'adoptions#new', as: 'adoption'
    post 'adopt', to: 'adoptions#create', as: 'send_adoption_form'
    put :update_photo, on: :member
  end
  get 'adoption', to: 'adoptions#new_preferences'
  post 'adoption', to: 'adoptions#send_preferences'
  resources :static_pages

  resources :articles do
    put :update_photo, on: :member
  end
  root 'static_pages#welcome'
  get 'contact-me', to: 'messages#new', as: 'new_message'
  post 'contact-me', to: 'messages#create', as: 'create_message'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/static_pages_controller.rb
# frozen_string_literal: true

class StaticPagesController < ApplicationController
  def welcome
    @animals = AnimalDecorator.decorate_collection(Animal.last(3))
    @article = Article.last.decorate
  end
end

app/helpers/static_pages_helper.rb
# frozen_string_literal: true

module StaticPagesHelper
end

app/views/static_pages/welcome.html.haml
%section.pets
  %div.pets
    %h1
      Poznaj naszych podopiecznych
    .card-deck
      - @animals.each do |animal|
        .col-4
          .card
            = link_to animal_path(animal) do
              %img.card-img-top{alt: "#{animal.name}", src: animal.main_image, id: "animal_image_main"}/
              .card-body
                %h5.card-title.name="#{animal.name}"
                %br
                %h5.card-title.age="#{animal.age} lat(a)"
  %p
  %a.btn.btn-success.more{:href => animals_path, :role => "button"} Pozostałe czworonogi

%section.help
  %div.overlay
    %div.row
      %div.container.col-5.cropped
        %div.help-headers
          %h1 ty również możesz zostać bohaterem
          %h2 10 1010 2300 0026 1395 1000 0025 2183
          %h3 Przekazując dowolną darowiznę na rzecz Domu “Bezpieczna Przystań”, pomagasz dbać o zdrowie i dobry stan naszych milusińskich.
      %div.col-5

.jumbotron
  %h1
    Nowości na blogu
    %p
    .row
      .col-12
        =link_to article_path(@article) do
          %h3 #{@article.title}
      .col-3
        %img.img-thumbnail{alt: @article.title, src: @article.main_image, id:"article_image_main"}/
      .col-8
        %p.lead #{@article.body}

  %p
  %a.btn.btn-success.btn-md{:href => articles_path, :role => "button"} Pozostałe artykuły