config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :user
  devise_scope :user do
    get 'admin', to: 'devise/sessions#new'
    post 'admin', to: 'devise/sessions#create'
  end
  resources :animals do
    get 'adopt', to: 'adoptions#new', as: 'adoption'
    post 'adopt', to: 'adoptions#create', as: 'send_adoption_form'
    put :update_photo, on: :member
  end
  get 'adoption', to: 'adoptions#new_preferences'
  post 'adoption', to: 'adoptions#send_preferences'
  resources :static_pages

  resources :articles do
    put :update_photo, on: :member
  end
  root 'static_pages#welcome'
  get 'contact-me', to: 'messages#new', as: 'new_message'
  post 'contact-me', to: 'messages#create', as: 'create_message'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/article.rb
# frozen_string_literal: true

class Article < ApplicationRecord
  validates :title, presence: true, length: { minimum: 10 }
  validates :body, presence: true, length: { minimum: 10 }
  has_many :images, as: :imageable
  attr_accessor :image_data
  accepts_nested_attributes_for :images
end

app/controllers/articles_controller.rb
# frozen_string_literal: true

class ArticlesController < ApplicationController
  before_action :find_article, only: %i[show edit update destroy update_photo]
  before_action :authorize_article, only: %i[edit update destroy update_photo]
  def index
    @articles = ArticleDecorator.decorate_collection(Article.all.paginate(page: params[:page], per_page: 7))
    respond_to do |format|
      format.html {}
      format.json { render json: @articles }
    end
  end

  def show
    @article = Article.find(params[:id]).decorate
    respond_to do |format|
      format.html {}
      format.json { render json: @article }
    end
  end

  def new
    @article = Article.new
    authorize @article
  end

  def create
    @article = Article.new(article_params)
    authorize @article
    if @article.save
      params[:article][:image_data]&.each do |file|
        @article.images.create!(image: file)
      end
      flash[:success] = 'Post opublikowany'
      redirect_to articles_path
    else
      render 'new'
    end
  end

  def edit; end

  def update
    if @article.update_attributes(article_params)
      @article.images.destroy_all
      params[:article][:image_data]&.each do |file|
        @article.images.create!(image: file)
      end
      flash[:success] = 'Post zaktualizowany'
      redirect_to @article
    else
      render 'edit'
    end
  end

  def update_photo
    @article.update_attributes(params.permit(:photo))
    redirect_to article_path
  end

  def destroy
    @article.destroy
    flash[:success] = 'Post usunięty'
    redirect_to articles_path
  end

  private

  def article_params
    params.require(:article).permit(:title, :body, image_data: [])
  end

  def find_article
    @article = Article.find(params[:id])
  end

  def authorize_article
    authorize @article
  end
end

app/helpers/articles_helper.rb
# frozen_string_literal: true

module ArticlesHelper
end

app/views/articles/_form.html.haml
.col-4
= simple_form_for(@article) do |form|
  = form.input :title, label: "Tytuł:"
  = form.input :body, label: "Treść:"
  = form.input :image_data, label: "Zdjęcia", as: :file, :input_html => { :multiple => true }, accept: 'image/png,image/gif,image/jpeg, image/jpg', name: 'article[images][][:image_data]'
  = form.button :submit, class: 'btn btn- btn-md'

app/views/articles/create.html.haml
%h1 Articles#create
%p Find me in app/views/articles/create.html.erb

app/views/articles/destroy.html.haml
%h1 Articles#destroy
%p Find me in app/views/articles/destroy.html.erb

app/views/articles/edit.html.haml
%h1 Articles#edit
= render 'form'

app/views/articles/index.html.haml
%h1 Co u nas słychać?
= will_paginate
- @articles.each do |article|
  .jumbotron
    .row
      .col-4
        %img.img-fluid{src: article.main_image}
      .col-6
        .h3
          .article-title
            = link_to article.title, article_path(article)
        .article-body
          = truncate(article.body, length: 1000)
      .col-2
        .row
          = social_share_button_tag(article.title, :allow_sites => %w(twitter))
          = social_share_button_tag(article.title, :allow_sites => %w(facebook), :url => article_url(article), desc: article.title)
        - if user_signed_in?
          .row
            = link_to 'Edytuj artykuł', edit_article_path(article), class: 'btn btn-warning btn-sm'
            = link_to 'Usuń artykuł', article_path(article), method: :delete, class: 'btn btn-danger btn-sm', data: { confirm: 'Czy na pewno chcesz usunąć ten artykuł?' }


= will_paginate

app/views/articles/new.html.haml
%h1 Nowy wpis
= render 'form'

app/views/articles/show.html.haml
-if user_signed_in?
  .row
    = link_to 'Edytuj artykuł', edit_article_path(@article), class: 'btn btn-warning btn-md'
    = link_to 'Usuń artykuł', article_path(@article), method: :delete, class: 'btn btn-danger btn-md', data: { confirm: 'Czy na pewno chcesz usunąć ten artykuł?' }

%h1
  =@article.title
.row
  .col-4
    %img.img-fluid{src: @article.main_image}
  .col-6
    = @article.body
%p
  -if @article.images.any?
    %strong Zdjęcia:
    .card-deck
      - @article.images.each do |image|
        -# - if image.image_url != @article.main_image
        .card
          %img.card-img-top{src: image.image_url, :id => "article_image_#{image.id}"}
            - if user_signed_in?
              .card-body
                = link_to 'Ustaw jako główne zdjęcie', update_photo_article_path(@article, photo: image.image_url), method: :put, class: 'btn btn-secondary btn-sm'

.row
  = social_share_button_tag(@article.title, :allow_sites => %w(twitter))
  = social_share_button_tag(@article.title, :allow_sites => %w(facebook), :url => article_url(@article), desc: @article.title)