config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :user
  devise_scope :user do
    get 'admin', to: 'devise/sessions#new'
    post 'admin', to: 'devise/sessions#create'
  end
  resources :animals do
    get 'adopt', to: 'adoptions#new', as: 'adoption'
    post 'adopt', to: 'adoptions#create', as: 'send_adoption_form'
    put :update_photo, on: :member
  end
  get 'adoption', to: 'adoptions#new_preferences'
  post 'adoption', to: 'adoptions#send_preferences'
  resources :static_pages

  resources :articles do
    put :update_photo, on: :member
  end
  root 'static_pages#welcome'
  get 'contact-me', to: 'messages#new', as: 'new_message'
  post 'contact-me', to: 'messages#create', as: 'create_message'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_animal_form.html.haml
.col-4
  = simple_form_for(@animal) do |form|
    = form.input :name
    = form.input :photo
    = form.input :breed
    = form.input :gender
    = form.input :size
    = form.input :purpose
    = form.input :age
    = form.input :for_kids
    = form.input :come_date
    = form.input :sterilization_date
    = form.input :vaccination_date
    = form.input :general_info
    = form.button :submit

app/views/shared/_facebook.html.haml
#facebook_slider_widget{:style => "display: none"}
  %script{:src => "http://webfrik.pl/widget/facebook_slider.html?fb_url=https://www.facebook.com/dom.tymczasowy.bezpieczna.przystan/&fb_width=400&fb_height=590&fb_faces=true&fb_stream=true&fb_header=true&fb_border=true&fb_theme=light&chx=787&speed=FAST&fb_pic=sign&position=LEFT", :type => "text/javascript"}

app/views/shared/_footer.html.haml
%nav.navbar.navbar-bottom.navbar-dark.bg-success
  %navbar-brand.mx-auto.text-center
    .p.font-weight-bolder Dom tymczasowy dla zwierząt
    .p.font-weight-bolder Bezpieczna Przystań

    .p Linarczyk 13C
    .p 86-300 Grudziądz

    .p Telefon: 757 577 543

    .p Numer konta bankowego:
    .p.font-weight-bold 10 1010 2300 0026 1395 1000 0025 2183

app/views/shared/_header.html.haml
%div.background
  %div.overlay
    %div.container
      %div.top-section
        %div.logo
          %div.logo-image
            %img{src: root_path + 'logo.png'}
          %h2
            Bezpieczna
            %br
            Przystań
        %nav.navbar.navbar-expand-lg
          %ul.nav.navbar-nav
            %li.nav-item
              = link_to "Blog", articles_path, class: 'nav-link'
            %li.nav-item
              = link_to "Nasi podopieczni", animals_path, class: 'nav-link'
            %li.nav-item
              = link_to "Kontakt", new_message_path, class: 'nav-link'
            %li.nav-item.adoption-button
              = link_to "Adopcja", new_message_path, class: 'nav-link'
            -if user_signed_in?
              %li.nav-item
                =link_to "Dodaj artykuł", new_article_path, class: 'btn btn-info btn-sm'
              %li.nav-item
                =link_to "Dodaj zwierzę", new_animal_path, class: 'btn btn-info btn-sm'
              %li.nav-item
                =link_to "Wyloguj", destroy_user_session_path, method: :delete, class: 'btn btn-danger btn-sm'
      %br
      %div.button-section
        %div.title
          %h2.main-title
            bezpieczna przystań
            %br
          %h2
            dla wszystkich czworonogów
    %p.notice= notice
    %p.alert= alert