config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :user
  devise_scope :user do
    get 'admin', to: 'devise/sessions#new'
    post 'admin', to: 'devise/sessions#create'
  end
  resources :animals do
    get 'adopt', to: 'adoptions#new', as: 'adoption'
    post 'adopt', to: 'adoptions#create', as: 'send_adoption_form'
    put :update_photo, on: :member
  end
  get 'adoption', to: 'adoptions#new_preferences'
  post 'adoption', to: 'adoptions#send_preferences'
  resources :static_pages

  resources :articles do
    put :update_photo, on: :member
  end
  root 'static_pages#welcome'
  get 'contact-me', to: 'messages#new', as: 'new_message'
  post 'contact-me', to: 'messages#create', as: 'create_message'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/animal.rb
# frozen_string_literal: true

class Animal < ApplicationRecord
  validates :name, presence: true, length: { minimum: 2, maximum: 30 }
  validates :gender, presence: true
  validates :size, presence: true
  validates :purpose, presence: true
  validates :for_kids, inclusion: { in: [true, false] }
  validates :age, presence: true, numericality: { less_than_or_equal_to: 30, only_integer: true }
  validates :general_info, length: { maximum: 1000 }
  validates :come_date, presence: true
  validates :breed, presence: true
  validates :type, presence: true, inclusion: { in: %w[Cat Dog] }
  has_many :images, as: :imageable
  attr_accessor :image_data
  accepts_nested_attributes_for :images
end

app/controllers/animals_controller.rb
# frozen_string_literal: true

class AnimalsController < ApplicationController
  before_action :find_animal, only: %i[edit update destroy update_photo]
  before_action :authorize_animal, only: %i[edit update destroy update_photo]

  def index
    @animals = AnimalDecorator.decorate_collection(Animal.all.paginate(page: params[:page], per_page: 6))
    respond_to do |format|
      format.html {}
      format.json { render json: @animals }
    end
  end

  def new
    @url = animals_path
    @animal = Animal.new
    authorize @animal
  end

  def create
    @animal = Animal.new(animal_params)
    authorize @animal
    if @animal.save
      params[:animal][:image_data]&.each do |file|
        @animal.images.create!(image: file)
      end
      flash[:success] = 'Pomyślnie dodano nowego zwierzaczka.'
      redirect_to animals_path
    else
      flash.now[:danger] = 'Nie udało się dodać nowego zwierzątka. Sprawdź błędy i spróbuj ponownie.'
      render :new
    end
  end

  def show
    @animal = Animal.find(params[:id]).decorate
    respond_to do |format|
      format.html {}
      format.json { render json: @animal }
    end
  end

  def edit
    @url = animal_path(@animal)
  end

  def update
    if @animal.update_attributes(animal_params)
      @animal.images.destroy_all
      params[:animal][:image_data]&.each do |file|
        @animal.images.create!(image: file)
      end
      flash[:success] = 'Dane zwierzaka zaktualizowane pomyślnie'
      redirect_to animal_path(@animal)
    else
      render 'edit'
    end
  end

  def update_photo
    @animal.update_attributes(params.permit(:photo))
    redirect_to animal_path
  end

  def destroy
    @animal.destroy
    flash[:success] = 'Zwierzątko zostało usunięte'
    redirect_to animals_path
  end

  private

  def animal_params
    params.require(:animal).permit(:name, :type, :gender, :size, :age,
                                   :purpose, :for_kids, :general_info, :come_date, :vaccination_date,
                                   :sterilization_date, :breed, :photo, image_data: [])
  end

  def find_animal
    @animal = Animal.find(params[:id])
  end

  def authorize_animal
    authorize @animal
  end
end

app/helpers/animals_helper.rb
# frozen_string_literal: true

module AnimalsHelper
end

app/views/animals/_animal_form.html.haml
.col-4
  = simple_form_for(@animal, as: :animal, url: @url) do |form|
    = form.input :type, label: "Gatunek:", collection: [["Pies", "Dog"], ["Kot", "Cat"]]
    = form.input :name, label: "Imię:"
    = form.input :image_data, label: "Zdjęcia", as: :file, :input_html => { :multiple => true }, accept: 'image/png,image/gif,image/jpeg, image/jpg', name: 'animal[images][][:image_data]'
    = form.input :breed, label: "Rasa:"
    = form.input :gender, label: "Płeć", collection: ["Pies", "Suka", "Kot", "Kotka"]
    = form.input :size, label: "Wielkość:"
    = form.input :purpose, label: "Przeznaczenie:"
    = form.input :age, label: "Wiek:"
    = form.input :for_kids, label: "Przyjazny dzieciom?"
    = form.input :come_date, label: "W bezpiecznej przystani od:"
    = form.input :sterilization_date, include_blank: true, label: "Data sterylizacji:"
    = form.input :vaccination_date, include_blank: true, label: "Data szczepienia:"
    = form.input :general_info, label: "Opis:"
    = form.button :submit, class: 'btn btn-success btn-md'

app/views/animals/adoption.html.haml
%h1 Formularz adopcyjny
%h2= @animal.name
.col-2
  %img.img-thumbnail{alt: @animal.name, src: @animal.main_image}
%p
%p W celu ułatwienia procesu związanego z adopcją, prosimy o wypełnienie poniższego formularza.

= simple_form_for @adoption, url: animal_send_adoption_form_path do |f|
  = f.input :name, label: 'Imię i nazwisko:'
  = f.input :email
  = f.input :phone_number, label: 'Nr telefonu'
  = f.input :where_keep, label: 'Gdzie pies będzie głównie przebywał?'
  = f.input :free_time, label: 'W jaki sposób spędzasz czas wolny?'
  = f.input :children_age, label: 'Czy masz dzieci, a jeżeli tak to w jakim wieku?'
  = f.input :other_animals, label: 'Czy posiadasz aktualnie jakieś zwierzęta, a jeżeli tak to jakie?'
  = f.input :had_dog, label: 'Czy miałes już wcześniej psa?'
  = f.input :hours_alone, label: 'Ile godzin w ciągu dnia pies pozostawałby sam?'
  = f.input :comments, label: 'Dodatkowe informacje, pytania, uwagi:'

  = f.button :submit, 'Wyślij'

app/views/animals/create.html.haml
%h1 Animals#create
%p Find me in app/views/animals/create.html.erb

app/views/animals/destroy.html.haml
%h1 Animals#destroy
%p Find me in app/views/animals/destroy.html.erb

app/views/animals/edit.html.haml
%h1 Animals#edit
= render 'animal_form'

app/views/animals/index.html.haml
%h1 Poznaj naszych podopiecznych!
%p
%p.lead Zachęcamy do zapoznania się z aktualnymi mieszkańcami Bezpiecznej Przystani. Zainteresowanych adopcją zapraszamy do kontaktu. Niezainteresowanych, do udostępniania na Facebooku i Tweeterze :)

= will_paginate
.card-deck
  - @animals.each do |animal|
    .col-4
      .card
        = link_to animal_path(animal) do
          %img.card-img-top{alt: "#{animal.name}", src: animal.main_image, id: "animal_image_main"}/
          .card-body
            %h5.card-title="#{animal.name}"
            .row.justify-content-end
              = social_share_button_tag("#{animal.name} szuka ciepłego domu!", :allow_sites => %w(twitter))
              = social_share_button_tag(animal.name, :allow_sites => %w(facebook), :url => animal_url(animal), desc: "#{animal.name} szuka ciepłego domu!")
            .row.justify-content-end
              -if user_signed_in?
                = link_to 'Edytuj', edit_animal_path(animal), class: 'btn btn-warning btn-sm'
                = link_to 'Usuń', animal_path(animal), method: :delete, class: 'btn btn-danger btn-sm', data: { confirm: 'Czy na pewno chcesz usunąć  tego zwierzaka?' }
.row
  = link_to "Dodaj zwierzę", new_animal_path, type: 'button', class: 'btn btn-success btn-lg'
= will_paginate

app/views/animals/new.html.haml
%h1 Dodaj nowe zwierzę
= render 'animal_form'

app/views/animals/show.html.haml
-if user_signed_in?
  = link_to 'Edytuj', edit_animal_path(@animal), class: 'btn btn-warning btn-md'
  = link_to 'Usuń', animal_path(@animal), method: :delete, class: 'btn btn-danger btn-md', data: { confirm: 'Czy na pewno chcesz usunąć  tego zwierzaka?' }
.row
  .col-12
    %h1 #{@animal.name}
  .col-4
    %img.img-thumbnail{alt: @animal.name, src: @animal.main_image, id:"animal_image_main"}
  .col-8
    %p Rasa: #{@animal.breed}
    %p Płeć: #{@animal.gender}
    %p Wielkość: #{@animal.size}
    %p Przeznaczenie: #{@animal.purpose}
    %p Wiek: #{@animal.age}
    %p Płeć: #{@animal.gender}
    %p #{@animal.kids?}
    %p W Bezpiecznej Przystani od: #{@animal.come_date}
    %p Data sterylizacji: #{@animal.sterilization_date}
    %p Data ostatniego szczepienia: #{@animal.vaccination_date}
    %p Szczegóły: #{@animal.general_info}
    = social_share_button_tag("#{@animal.name} szuka ciepłego domu!", :allow_sites => %w(twitter))
    = social_share_button_tag(@animal.name, :allow_sites => %w(facebook), :url => animal_url(@animal), desc: "#{@animal.name} szuka ciepłego domu!")
    %p
      = link_to 'PSYgarnij mnie :)', animal_adoption_path(@animal), method: :get, class: 'btn btn-success btn-lg'

%p
%p
  -if @animal.images.count > 1
    %strong Zdjęcia:
    .card-deck
      - @animal.images.each do |image|
        -# - if image.image_url != @animal.main_image
        .card
          %img.card-img-top{src: image.image_url}
            - if user_signed_in?
              .card-body
                = link_to 'Ustaw jako główne zdjęcie', update_photo_animal_path(@animal, photo: image.image_url), method: :put, class: 'btn btn-secondary btn-sm'

app/views/animals/update.html.haml
%h1 Animals#update
%p Find me in app/views/animals/update.html.erb